# Generated by Django 2.2.8 on 2020-01-20 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_service_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveservice',
            name='notes',
            field=models.TextField(default='TEST'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eveinvoice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dae43654-7de2-4914-a326-d0f7b70e8cd9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
