# Generated by Django 2.2.8 on 2020-01-20 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_service_manager', '0003_auto_20200120_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eveinvoice',
            old_name='pending',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='eveinvoice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e329d22e-232e-42d4-aa84-6cd38ce30cd3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
