# Generated by Django 2.2.8 on 2020-01-20 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_service_manager', '0004_auto_20200120_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveinvoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eveinvoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
